// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_580843432);    // assets/frame_79_delay-1.33s.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
